"""initial schema

Revision ID: 9b12b308522e
Revises:
Create Date: 2026-06-13 14:05:19.982729
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9b12b308522e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor"), "audit_log", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_log_entry_hash"), "audit_log", ["entry_hash"], unique=False)
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "employees",
        sa.Column("hr_external_id", sa.String(length=128), nullable=False),
        sa.Column("work_email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role", sa.Enum("EMPLOYEE", "MANAGER", "HR", "ADMIN", name="role"), nullable=False
        ),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="employeestatus"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.id"],
            name=op.f("fk_employees_manager_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("work_email", name="uq_employees_work_email"),
    )
    op.create_index(
        op.f("ix_employees_hr_external_id"), "employees", ["hr_external_id"], unique=True
    )
    op.create_index(op.f("ix_employees_is_active"), "employees", ["is_active"], unique=False)
    op.create_index(op.f("ix_employees_manager_id"), "employees", ["manager_id"], unique=False)
    op.create_index(op.f("ix_employees_status"), "employees", ["status"], unique=False)
    op.create_index(op.f("ix_employees_work_email"), "employees", ["work_email"], unique=False)
    op.create_table(
        "devices",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_sequence", sa.BigInteger(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_devices_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(op.f("ix_devices_employee_id"), "devices", ["employee_id"], unique=False)
    op.create_index(op.f("ix_devices_is_revoked"), "devices", ["is_revoked"], unique=False)
    op.create_index(op.f("ix_devices_token_hash"), "devices", ["token_hash"], unique=True)
    op.create_table(
        "activity_samples",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("client_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active_window", sa.String(length=512), nullable=True),
        sa.Column("idle_seconds", sa.Integer(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_activity_samples_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_activity_samples_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_samples")),
        sa.UniqueConstraint("device_id", "sequence", name="uq_activity_device_sequence"),
    )
    op.create_index(
        "ix_activity_employee_received",
        "activity_samples",
        ["employee_id", "received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_samples_device_id"), "activity_samples", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_samples_employee_id"), "activity_samples", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_samples_received_at"), "activity_samples", ["received_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_samples_received_at"), table_name="activity_samples")
    op.drop_index(op.f("ix_activity_samples_employee_id"), table_name="activity_samples")
    op.drop_index(op.f("ix_activity_samples_device_id"), table_name="activity_samples")
    op.drop_index("ix_activity_employee_received", table_name="activity_samples")
    op.drop_table("activity_samples")
    op.drop_index(op.f("ix_devices_token_hash"), table_name="devices")
    op.drop_index(op.f("ix_devices_is_revoked"), table_name="devices")
    op.drop_index(op.f("ix_devices_employee_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_employees_work_email"), table_name="employees")
    op.drop_index(op.f("ix_employees_status"), table_name="employees")
    op.drop_index(op.f("ix_employees_manager_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_is_active"), table_name="employees")
    op.drop_index(op.f("ix_employees_hr_external_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entry_hash"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
