"""envsync

Revision ID: eecb30a20328
Revises: add_ping_update_kind
Create Date: 2026-06-25 11:13:16.738961
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eecb30a20328"
down_revision: str | None = "add_ping_update_kind"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "env_access_tokens",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_env_access_tokens_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_access_tokens")),
    )
    op.create_index(
        op.f("ix_env_access_tokens_employee_id"), "env_access_tokens", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_env_access_tokens_is_revoked"), "env_access_tokens", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_env_access_tokens_token_hash"), "env_access_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "env_projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["employees.id"],
            name=op.f("fk_env_projects_owner_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_projects")),
    )
    op.create_index(
        op.f("ix_env_projects_department"), "env_projects", ["department"], unique=False
    )
    op.create_index(op.f("ix_env_projects_owner_id"), "env_projects", ["owner_id"], unique=False)
    op.create_table(
        "env_project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "EDITOR", "VIEWER", name="envmemberrole"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_env_project_members_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["env_projects.id"],
            name=op.f("fk_env_project_members_project_id_env_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_project_members")),
        sa.UniqueConstraint(
            "project_id", "employee_id", name="uq_env_project_members_project_employee"
        ),
    )
    op.create_index(
        op.f("ix_env_project_members_employee_id"),
        "env_project_members",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_env_project_members_project_id"),
        "env_project_members",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "env_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("content_encrypted", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_env_versions_created_by_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["env_versions.id"],
            name=op.f("fk_env_versions_parent_version_id_env_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["env_projects.id"],
            name=op.f("fk_env_versions_project_id_env_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_versions")),
    )
    op.create_index(
        "ix_env_versions_project_env_created",
        "env_versions",
        ["project_id", "environment", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_env_versions_project_id"), "env_versions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_env_versions_project_id"), table_name="env_versions")
    op.drop_index("ix_env_versions_project_env_created", table_name="env_versions")
    op.drop_table("env_versions")
    op.drop_index(op.f("ix_env_project_members_project_id"), table_name="env_project_members")
    op.drop_index(op.f("ix_env_project_members_employee_id"), table_name="env_project_members")
    op.drop_table("env_project_members")
    op.drop_index(op.f("ix_env_projects_owner_id"), table_name="env_projects")
    op.drop_index(op.f("ix_env_projects_department"), table_name="env_projects")
    op.drop_table("env_projects")
    op.drop_index(op.f("ix_env_access_tokens_token_hash"), table_name="env_access_tokens")
    op.drop_index(op.f("ix_env_access_tokens_is_revoked"), table_name="env_access_tokens")
    op.drop_index(op.f("ix_env_access_tokens_employee_id"), table_name="env_access_tokens")
    op.drop_table("env_access_tokens")
    # The Enum type is created implicitly by create_table; drop it explicitly.
    sa.Enum(name="envmemberrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
